image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000

vscode:
  extensions:
    - VisualStudioExptTeam.vscodeintellicode@1.1.9:osawgVS7+7lo2813SXOJng==
    - zxh404.vscode-proto3@0.4.2:ZnPmyF/Pb8AIWeCqc83gPw==
